[package]
name = "rust-boilerplate"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
better-panic = "0.3"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.8.1"
clap = { version = "4", features = ["derive", "cargo"] }
crossbeam-channel = "0.5"
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
serde = "1"
serde_derive = "1"
sqlx = { version = "0.6", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "macros",
  "chrono",
] }
strum = "0.24"
strum_macros = "0.24"
tokio = { version = "1.28", features = ["rt-multi-thread", "time", "macros"] }

[dev-dependencies]
pretty_assertions = "1"
rstest = "0.16"
